import AppKit
import CoreServices
import Foundation
import UniformTypeIdentifiers

struct AppConfig {
    static let defaultFileExtensions = ["ts", "rs", "py", "json", "css", "scss", "less", "sass", "c", "cpp"]

    var language: String = "auto"
    var terminal: String = "auto"
    var nvimPath: String = "/opt/homebrew/bin/nvim"
    var remoteOpen: String = "tab"
    var defaultFileExtensions: [String] = Self.defaultFileExtensions
    var tmuxMode: String = "never"
    var tmuxSession: String = ""
}

final class ConfigStore {
    static let shared = ConfigStore()

    let configURL: URL

    private init() {
        configURL = FileManager.default
            .homeDirectoryForCurrentUser
            .appendingPathComponent(".config/open-in-nvim/config")
    }

    func load() -> AppConfig {
        var config = AppConfig()

        guard let content = try? String(contentsOf: configURL, encoding: .utf8) else {
            if let nvim = findExecutable("nvim") {
                config.nvimPath = nvim
            }
            return config
        }

        for rawLine in content.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty, !line.hasPrefix("#"), let equalsIndex = line.firstIndex(of: "=") else {
                continue
            }

            let key = String(line[..<equalsIndex])
            var value = String(line[line.index(after: equalsIndex)...])
            value = value.trimmingCharacters(in: .whitespaces)
            value = value.trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))

            switch key {
            case "OPEN_IN_NVIM_LANGUAGE":
                config.language = value
            case "OPEN_IN_NVIM_TERMINAL":
                config.terminal = value
            case "OPEN_IN_NVIM_NVIM":
                config.nvimPath = value
            case "OPEN_IN_NVIM_REMOTE_OPEN":
                config.remoteOpen = value
            case "OPEN_IN_NVIM_DEFAULT_EXTENSIONS":
                config.defaultFileExtensions = Self.parseExtensions(value)
            case "OPEN_IN_NVIM_TMUX":
                config.tmuxMode = value
            case "OPEN_IN_NVIM_TMUX_SESSION":
                config.tmuxSession = value
            default:
                continue
            }
        }

        return config
    }

    func save(_ config: AppConfig) throws {
        try FileManager.default.createDirectory(
            at: configURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let lines = [
            "# Generated by Open In Nvim settings",
            "OPEN_IN_NVIM_LANGUAGE=\(shellQuote(config.language))",
            "OPEN_IN_NVIM_TERMINAL=\(shellQuote(config.terminal))",
            "OPEN_IN_NVIM_NVIM=\(shellQuote(config.nvimPath))",
            "OPEN_IN_NVIM_REMOTE_OPEN=\(shellQuote(config.remoteOpen))",
            "OPEN_IN_NVIM_DEFAULT_EXTENSIONS=\(shellQuote(config.defaultFileExtensions.joined(separator: " ")))",
            "OPEN_IN_NVIM_TMUX=\(shellQuote(config.tmuxMode))",
            "OPEN_IN_NVIM_TMUX_SESSION=\(shellQuote(config.tmuxSession))"
        ].compactMap { $0 }

        try (lines.joined(separator: "\n") + "\n").write(to: configURL, atomically: true, encoding: .utf8)
    }

    static func parseExtensions(_ value: String) -> [String] {
        let separators = CharacterSet(charactersIn: ",，;； \n\t")
        var seen = Set<String>()

        return value
            .components(separatedBy: separators)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .map { $0.hasPrefix(".") ? String($0.dropFirst()) : $0 }
            .map { $0.lowercased() }
            .filter { !$0.isEmpty }
            .filter { extensionName in
                if seen.contains(extensionName) {
                    return false
                }
                seen.insert(extensionName)
                return true
            }
    }

    private func findExecutable(_ name: String) -> String? {
        let paths = [
            "/opt/homebrew/bin/\(name)",
            "/usr/local/bin/\(name)",
            "/usr/bin/\(name)",
            "/bin/\(name)"
        ]

        return paths.first { FileManager.default.isExecutableFile(atPath: $0) }
    }

    private func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

enum AppText {
    static func resolvedLanguage(_ preference: String) -> String {
        if preference == "zh-Hans" || preference == "en" {
            return preference
        }

        for language in Locale.preferredLanguages {
            if language.lowercased().hasPrefix("zh") {
                return "zh-Hans"
            }
            if language.lowercased().hasPrefix("en") {
                return "en"
            }
        }

        return "en"
    }

    static func text(_ key: String, language preference: String) -> String {
        let language = resolvedLanguage(preference)
        return translations[language]?[key] ?? translations["en"]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "zh-Hans": [
            "window.subtitle": "设置 Finder 打开文件时如何进入 Neovim。",
            "section.general": "常规",
            "section.newInstance": "新建实例",
            "section.defaultOpen": "默认打开方式",
            "section.advanced": "高级",
            "field.language": "语言",
            "field.terminal": "终端",
            "field.existingNvim": "已有 nvim",
            "field.nvimPlugin": "nvim 插件",
            "field.tmux": "tmux",
            "field.session": "session",
            "field.defaultExtensions": "默认扩展名",
            "field.customTerminal": "自定义终端",
            "field.nvimPath": "nvim 路径",
            "button.save": "保存",
            "button.add": "添加",
            "button.installPlugin": "安装插件",
            "placeholder.customTerminal": "例如 WezTerm、Alacritty",
            "placeholder.tmuxSession": "留空则创建新 session",
            "placeholder.extension": "例如 md",
            "status.configFile": "配置文件：%@",
            "status.saved": "已保存，并已设置默认打开方式：%@",
            "status.partialDefaultFailure": "配置已保存，部分默认打开方式设置失败：%@",
            "status.enterExtension": "请输入要添加的扩展名。",
            "status.addedExtensions": "已添加：%@，保存后生效。",
            "status.pluginInstalled": "已写入 nvim 插件配置：%@",
            "error.saveFailed": "保存失败",
            "error.installFailed": "安装失败",
            "error.openFailed": "打开失败",
            "error.scriptNoMessage": "打开失败，脚本没有返回错误信息。",
            "error.bundleId": "无法读取当前 App 的 Bundle Identifier。",
            "error.unknownType": ".%@：无法识别文件类型",
            "error.launchServices": ".%@：LaunchServices 返回 %d",
            "option.language.auto": "自动",
            "option.language.zhHans": "简体中文",
            "option.language.en": "English",
            "option.terminal.auto": "自动选择",
            "option.terminal.ghostty": "Ghostty",
            "option.terminal.alacritty": "Alacritty",
            "option.terminal.iterm": "iTerm2",
            "option.terminal.terminal": "Terminal.app",
            "option.terminal.custom": "自定义 App 名称",
            "option.remote.tab": "新标签页",
            "option.remote.split": "水平窗口",
            "option.remote.vsplit": "垂直窗口",
            "option.remote.buffer": "只打开 buffer",
            "option.tmux.never": "关闭",
            "option.tmux.auto": "自动",
            "option.tmux.always": "始终使用"
        ],
        "en": [
            "window.subtitle": "Choose how Finder opens files in Neovim.",
            "section.general": "General",
            "section.newInstance": "New Instance",
            "section.defaultOpen": "Default Apps",
            "section.advanced": "Advanced",
            "field.language": "Language",
            "field.terminal": "Terminal",
            "field.existingNvim": "Existing nvim",
            "field.nvimPlugin": "nvim plugin",
            "field.tmux": "tmux",
            "field.session": "Session",
            "field.defaultExtensions": "File extensions",
            "field.customTerminal": "Custom terminal",
            "field.nvimPath": "nvim path",
            "button.save": "Save",
            "button.add": "Add",
            "button.installPlugin": "Install plugin",
            "placeholder.customTerminal": "For example WezTerm or Alacritty",
            "placeholder.tmuxSession": "Empty creates a new session",
            "placeholder.extension": "For example md",
            "status.configFile": "Config file: %@",
            "status.saved": "Saved and set default apps for: %@",
            "status.partialDefaultFailure": "Config saved, but some default app changes failed: %@",
            "status.enterExtension": "Enter a file extension to add.",
            "status.addedExtensions": "Added %@. Save to apply.",
            "status.pluginInstalled": "Wrote nvim plugin config: %@",
            "error.saveFailed": "Save Failed",
            "error.installFailed": "Install Failed",
            "error.openFailed": "Open Failed",
            "error.scriptNoMessage": "Open failed. The script did not return an error message.",
            "error.bundleId": "Could not read this app's Bundle Identifier.",
            "error.unknownType": ".%@: unknown file type",
            "error.launchServices": ".%@: LaunchServices returned %d",
            "option.language.auto": "Automatic",
            "option.language.zhHans": "Simplified Chinese",
            "option.language.en": "English",
            "option.terminal.auto": "Automatic",
            "option.terminal.ghostty": "Ghostty",
            "option.terminal.alacritty": "Alacritty",
            "option.terminal.iterm": "iTerm2",
            "option.terminal.terminal": "Terminal.app",
            "option.terminal.custom": "Custom app name",
            "option.remote.tab": "New tab",
            "option.remote.split": "Horizontal split",
            "option.remote.vsplit": "Vertical split",
            "option.remote.buffer": "Buffer only",
            "option.tmux.never": "Off",
            "option.tmux.auto": "Automatic",
            "option.tmux.always": "Always"
        ]
    ]
}

final class OpenInNvimRunner {
    private let scriptPath: String

    init() {
        if let resourcePath = Bundle.main.resourcePath {
            self.scriptPath = (resourcePath as NSString).appendingPathComponent("open-in-nvim.sh")
        } else {
            self.scriptPath = "./open-in-nvim.sh"
        }
    }

    func open(_ urls: [URL], completion: ((String?) -> Void)? = nil) {
        guard !urls.isEmpty else { return }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.arguments = [scriptPath] + urls.map { $0.path }

        let errorPipe = Pipe()
        process.standardError = errorPipe

        process.terminationHandler = { process in
            let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
            let errorText = String(data: errorData, encoding: .utf8)?
                .trimmingCharacters(in: .whitespacesAndNewlines)

            DispatchQueue.main.async {
                if process.terminationStatus == 0 {
                    completion?(nil)
                } else {
                    let language = ConfigStore.shared.load().language
                    let fallback = AppText.text("error.scriptNoMessage", language: language)
                    completion?(errorText?.isEmpty == false ? errorText : fallback)
                }
            }
        }

        do {
            try process.run()
        } catch {
            completion?(error.localizedDescription)
        }
    }
}

enum DefaultAppRegistration {
    static func registerDefaultHandlers(for extensions: [String], language: String) -> [String] {
        guard let bundleID = Bundle.main.bundleIdentifier else {
            return [AppText.text("error.bundleId", language: language)]
        }

        var failures: [String] = []

        for fileExtension in extensions {
            guard let type = UTType(filenameExtension: fileExtension) else {
                failures.append(String(format: AppText.text("error.unknownType", language: language), fileExtension))
                continue
            }

            let status = LSSetDefaultRoleHandlerForContentType(
                type.identifier as CFString,
                .all,
                bundleID as CFString
            )

            if status != noErr {
                failures.append(String(format: AppText.text("error.launchServices", language: language), fileExtension, status))
            }
        }

        return failures
    }
}

enum NvimPluginInstaller {
    static var pluginSpecURL: URL {
        FileManager.default
            .homeDirectoryForCurrentUser
            .appendingPathComponent(".config/nvim/lua/plugins/open-in-nvim.lua")
    }

    static func install() throws -> URL {
        let url = pluginSpecURL
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try pluginSpec.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static let pluginSpec = """
    return {
      "pzehrel/open-in-nvim",
      lazy = false,
      config = function(plugin)
        vim.opt.runtimepath:prepend(plugin.dir .. "/nvim-plugin")
        require("open-in-nvim").setup()
      end,
    }
    """
}

final class SettingsWindowController: NSWindowController {
    private let languagePopup = NSPopUpButton()
    private let terminalPopup = NSPopUpButton()
    private let customTerminalField = NSTextField()
    private let nvimPathField = NSTextField()
    private let remoteOpenPopup = NSPopUpButton()
    private let tmuxModePopup = NSPopUpButton()
    private let tmuxSessionField = NSTextField()
    private let extensionOptionsStack = NSStackView()
    private let newExtensionField = NSTextField()
    private let statusLabel = NSTextField(labelWithString: "")
    private let configStore = ConfigStore.shared
    private let runner: OpenInNvimRunner
    private var currentLanguage: String = "auto"
    private var extensionOptions: [String] = AppConfig.defaultFileExtensions
    private var extensionButtons: [String: NSButton] = [:]

    private let languageOptions: [(key: String, value: String)] = [
        ("option.language.auto", "auto"),
        ("option.language.zhHans", "zh-Hans"),
        ("option.language.en", "en")
    ]

    private let terminalOptions: [(key: String, value: String)] = [
        ("option.terminal.auto", "auto"),
        ("option.terminal.ghostty", "ghostty"),
        ("option.terminal.alacritty", "alacritty"),
        ("option.terminal.iterm", "iterm"),
        ("option.terminal.terminal", "terminal"),
        ("option.terminal.custom", "custom")
    ]

    private let remoteOpenOptions: [(key: String, value: String)] = [
        ("option.remote.tab", "tab"),
        ("option.remote.split", "split"),
        ("option.remote.vsplit", "vsplit"),
        ("option.remote.buffer", "buffer")
    ]

    private let tmuxModeOptions: [(key: String, value: String)] = [
        ("option.tmux.never", "never"),
        ("option.tmux.auto", "auto"),
        ("option.tmux.always", "always")
    ]

    init(runner: OpenInNvimRunner) {
        self.runner = runner
        self.currentLanguage = configStore.load().language

        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 680, height: 680),
            styleMask: [.titled, .closable, .miniaturizable],
            backing: .buffered,
            defer: false
        )
        window.title = "Open In Nvim"
        window.center()

        super.init(window: window)
        buildUI()
        loadConfig()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    private func buildUI() {
        guard let contentView = window?.contentView else { return }

        setPopup(languagePopup, options: languageOptions, selectedValue: currentLanguage)
        languagePopup.target = self
        languagePopup.action = #selector(languageChanged)
        setPopup(terminalPopup, options: terminalOptions, selectedValue: "auto")
        terminalPopup.target = self
        terminalPopup.action = #selector(terminalChanged)
        setPopup(remoteOpenPopup, options: remoteOpenOptions, selectedValue: "tab")
        setPopup(tmuxModePopup, options: tmuxModeOptions, selectedValue: "never")
        tmuxModePopup.target = self
        tmuxModePopup.action = #selector(tmuxModeChanged)

        customTerminalField.placeholderString = t("placeholder.customTerminal")
        nvimPathField.placeholderString = "/opt/homebrew/bin/nvim"
        tmuxSessionField.placeholderString = t("placeholder.tmuxSession")
        newExtensionField.placeholderString = t("placeholder.extension")

        extensionOptionsStack.orientation = .vertical
        extensionOptionsStack.spacing = 8
        extensionOptionsStack.alignment = .leading

        let addExtensionButton = NSButton(title: t("button.add"), target: self, action: #selector(addExtension))
        addExtensionButton.bezelStyle = .rounded

        let addExtensionStack = NSStackView(views: [newExtensionField, addExtensionButton])
        addExtensionStack.orientation = .horizontal
        addExtensionStack.spacing = 8
        addExtensionStack.alignment = .centerY
        addExtensionStack.distribution = .fill
        newExtensionField.widthAnchor.constraint(equalToConstant: 180).isActive = true

        let extensionControl = NSStackView(views: [extensionOptionsStack, addExtensionStack])
        extensionControl.orientation = .vertical
        extensionControl.spacing = 10
        extensionControl.alignment = .leading

        statusLabel.textColor = .secondaryLabelColor
        statusLabel.lineBreakMode = .byWordWrapping

        let saveButton = NSButton(title: t("button.save"), target: self, action: #selector(saveConfig))
        saveButton.bezelStyle = .rounded
        saveButton.keyEquivalent = "\r"

        let installPluginButton = NSButton(title: t("button.installPlugin"), target: self, action: #selector(installNvimPlugin))
        installPluginButton.bezelStyle = .rounded

        let buttonSpacer = NSView()
        buttonSpacer.setContentHuggingPriority(.defaultLow, for: .horizontal)
        let buttonStack = NSStackView(views: [buttonSpacer, saveButton])
        buttonStack.orientation = .horizontal
        buttonStack.spacing = 8
        buttonStack.alignment = .centerY
        buttonStack.distribution = .fill

        let titleLabel = NSTextField(labelWithString: "Open In Nvim")
        titleLabel.font = .boldSystemFont(ofSize: 24)

        let subtitleLabel = NSTextField(labelWithString: t("window.subtitle"))
        subtitleLabel.font = .systemFont(ofSize: 13)
        subtitleLabel.textColor = .secondaryLabelColor

        let headerStack = NSStackView(views: [titleLabel, subtitleLabel])
        headerStack.orientation = .vertical
        headerStack.spacing = 4
        headerStack.alignment = .leading

        let generalForm = form(views: [
            [label(t("field.language")), languagePopup],
            [label(t("field.terminal")), terminalPopup],
            [label(t("field.existingNvim")), remoteOpenPopup],
            [label(t("field.nvimPlugin")), installPluginButton]
        ])

        let newInstanceForm = form(views: [
            [label(t("field.tmux")), tmuxModePopup],
            [label(t("field.session")), tmuxSessionField]
        ])

        let extensionForm = form(views: [
            [label(t("field.defaultExtensions")), extensionControl]
        ])

        let advancedForm = form(views: [
            [label(t("field.customTerminal")), customTerminalField],
            [label(t("field.nvimPath")), nvimPathField]
        ])

        let statusSeparator = NSBox()
        statusSeparator.boxType = .separator
        statusSeparator.translatesAutoresizingMaskIntoConstraints = false
        statusSeparator.heightAnchor.constraint(equalToConstant: 1).isActive = true

        let stack = NSStackView(views: [
            headerStack,
            section(title: t("section.general"), content: generalForm),
            section(title: t("section.newInstance"), content: newInstanceForm),
            section(title: t("section.defaultOpen"), content: extensionForm),
            section(title: t("section.advanced"), content: advancedForm),
            statusSeparator,
            statusLabel,
            buttonStack
        ])
        stack.orientation = .vertical
        stack.spacing = 16
        stack.alignment = .leading
        stack.translatesAutoresizingMaskIntoConstraints = false

        contentView.addSubview(stack)

        NSLayoutConstraint.activate([
            stack.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 28),
            stack.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -28),
            stack.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 24),
            stack.bottomAnchor.constraint(lessThanOrEqualTo: contentView.bottomAnchor, constant: -24),
            statusLabel.widthAnchor.constraint(equalTo: stack.widthAnchor),
            buttonStack.widthAnchor.constraint(equalTo: stack.widthAnchor)
        ])
    }

    private func t(_ key: String) -> String {
        AppText.text(key, language: currentLanguage)
    }

    private func setPopup(_ popup: NSPopUpButton, options: [(key: String, value: String)], selectedValue: String) {
        popup.removeAllItems()
        popup.addItems(withTitles: options.map { t($0.key) })

        if let index = options.firstIndex(where: { $0.value == selectedValue }) {
            popup.selectItem(at: index)
        } else {
            popup.selectItem(at: 0)
        }
    }

    private func rebuildUI(with config: AppConfig) {
        window?.contentView?.subviews.forEach { $0.removeFromSuperview() }
        extensionButtons.removeAll()
        buildUI()
        applyConfig(config)
    }

    private func form(views: [[NSView]]) -> NSGridView {
        let grid = NSGridView(views: views)
        grid.rowSpacing = 10
        grid.columnSpacing = 14
        grid.column(at: 0).xPlacement = .trailing
        grid.column(at: 1).width = 470
        return grid
    }

    private func section(title: String, content: NSView) -> NSStackView {
        let titleLabel = NSTextField(labelWithString: title)
        titleLabel.font = .boldSystemFont(ofSize: 13)
        titleLabel.textColor = .labelColor

        let separator = NSBox()
        separator.boxType = .separator
        separator.translatesAutoresizingMaskIntoConstraints = false
        separator.heightAnchor.constraint(equalToConstant: 1).isActive = true

        let headingStack = NSStackView(views: [titleLabel, separator])
        headingStack.orientation = .horizontal
        headingStack.spacing = 10
        headingStack.alignment = .centerY
        headingStack.distribution = .fill
        separator.setContentHuggingPriority(.defaultLow, for: .horizontal)

        let stack = NSStackView(views: [headingStack, content])
        stack.orientation = .vertical
        stack.spacing = 10
        stack.alignment = .leading
        stack.translatesAutoresizingMaskIntoConstraints = false
        headingStack.widthAnchor.constraint(equalTo: stack.widthAnchor).isActive = true
        return stack
    }

    private func label(_ text: String) -> NSTextField {
        let field = NSTextField(labelWithString: text)
        field.textColor = .secondaryLabelColor
        return field
    }

    private func loadConfig() {
        applyConfig(configStore.load())
    }

    private func applyConfig(_ config: AppConfig) {
        currentLanguage = config.language
        setPopup(languagePopup, options: languageOptions, selectedValue: config.language)
        let knownIndex = terminalOptions.firstIndex { $0.value == config.terminal && $0.value != "custom" }

        if let knownIndex {
            terminalPopup.selectItem(at: knownIndex)
            customTerminalField.stringValue = ""
        } else {
            if let customIndex = terminalOptions.firstIndex(where: { $0.value == "custom" }) {
                terminalPopup.selectItem(at: customIndex)
            }
            customTerminalField.stringValue = config.terminal
        }

        nvimPathField.stringValue = config.nvimPath
        tmuxSessionField.stringValue = config.tmuxSession
        setExtensionOptions(selectedExtensions: config.defaultFileExtensions)
        if let remoteIndex = remoteOpenOptions.firstIndex(where: { $0.value == config.remoteOpen }) {
            remoteOpenPopup.selectItem(at: remoteIndex)
        } else {
            remoteOpenPopup.selectItem(at: 0)
        }
        if let tmuxIndex = tmuxModeOptions.firstIndex(where: { $0.value == config.tmuxMode }) {
            tmuxModePopup.selectItem(at: tmuxIndex)
        } else {
            tmuxModePopup.selectItem(at: 0)
        }
        terminalChanged()
        tmuxModeChanged()
        statusLabel.stringValue = String(format: t("status.configFile"), configStore.configURL.path)
    }

    @objc private func terminalChanged() {
        let isCustom = selectedTerminalValue() == "custom"
        customTerminalField.isEnabled = isCustom
        customTerminalField.alphaValue = isCustom ? 1 : 0.45
    }

    @objc private func languageChanged() {
        var config = currentConfig()
        currentLanguage = selectedLanguageValue()
        config.language = currentLanguage
        rebuildUI(with: config)
    }

    @objc private func tmuxModeChanged() {
        let enabled = selectedTmuxModeValue() != "never"
        tmuxSessionField.isEnabled = enabled
        tmuxSessionField.alphaValue = enabled ? 1 : 0.45
    }

    @objc private func saveConfig() {
        do {
            let config = currentConfig()
            try configStore.save(config)
            let failures = DefaultAppRegistration.registerDefaultHandlers(
                for: config.defaultFileExtensions,
                language: config.language
            )
            let extensionsText = config.defaultFileExtensions.map { ".\($0)" }.joined(separator: " ")
            if failures.isEmpty {
                statusLabel.stringValue = String(format: t("status.saved"), extensionsText)
            } else {
                statusLabel.stringValue = String(format: t("status.partialDefaultFailure"), failures.joined(separator: "; "))
            }
        } catch {
            showError(t("error.saveFailed"), error.localizedDescription)
        }
    }

    @objc private func installNvimPlugin() {
        do {
            let url = try NvimPluginInstaller.install()
            statusLabel.stringValue = String(format: t("status.pluginInstalled"), url.path)
        } catch {
            showError(t("error.installFailed"), error.localizedDescription)
        }
    }

    private func currentConfig() -> AppConfig {
        let selected = selectedTerminalValue()
        let terminal = selected == "custom"
            ? customTerminalField.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
            : selected

        return AppConfig(
            language: selectedLanguageValue(),
            terminal: terminal.isEmpty ? "auto" : terminal,
            nvimPath: nvimPathField.stringValue.trimmingCharacters(in: .whitespacesAndNewlines),
            remoteOpen: selectedRemoteOpenValue(),
            defaultFileExtensions: selectedFileExtensions(),
            tmuxMode: selectedTmuxModeValue(),
            tmuxSession: normalizedTmuxSession()
        )
    }

    @objc private func addExtension() {
        let parsed = ConfigStore.parseExtensions(newExtensionField.stringValue)
        guard !parsed.isEmpty else {
            statusLabel.stringValue = t("status.enterExtension")
            return
        }

        addExtensionOptions(parsed, checked: true)
        newExtensionField.stringValue = ""
        statusLabel.stringValue = String(
            format: t("status.addedExtensions"),
            parsed.map { ".\($0)" }.joined(separator: " ")
        )
    }

    private func selectedLanguageValue() -> String {
        let index = languagePopup.indexOfSelectedItem
        guard languageOptions.indices.contains(index) else { return "auto" }
        return languageOptions[index].value
    }

    private func selectedTerminalValue() -> String {
        let index = terminalPopup.indexOfSelectedItem
        guard terminalOptions.indices.contains(index) else { return "auto" }
        return terminalOptions[index].value
    }

    private func selectedRemoteOpenValue() -> String {
        let index = remoteOpenPopup.indexOfSelectedItem
        guard remoteOpenOptions.indices.contains(index) else { return "tab" }
        return remoteOpenOptions[index].value
    }

    private func selectedTmuxModeValue() -> String {
        let index = tmuxModePopup.indexOfSelectedItem
        guard tmuxModeOptions.indices.contains(index) else { return "never" }
        return tmuxModeOptions[index].value
    }

    private func normalizedTmuxSession() -> String {
        tmuxSessionField.stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func selectedFileExtensions() -> [String] {
        extensionOptions.filter { extensionButtons[$0]?.state == .on }
    }

    private func setExtensionOptions(selectedExtensions: [String]) {
        extensionOptions = AppConfig.defaultFileExtensions
        extensionButtons.removeAll()

        let selected = Set(selectedExtensions)
        for extensionName in selectedExtensions where !extensionOptions.contains(extensionName) {
            extensionOptions.append(extensionName)
        }

        rebuildExtensionOptions(checkedExtensions: selected)
    }

    private func addExtensionOptions(_ extensionNames: [String], checked: Bool) {
        for extensionName in extensionNames where !extensionOptions.contains(extensionName) {
            extensionOptions.append(extensionName)
        }

        var selected = Set(selectedFileExtensions())
        if checked {
            selected.formUnion(extensionNames)
        }
        rebuildExtensionOptions(checkedExtensions: selected)
    }

    private func rebuildExtensionOptions(checkedExtensions: Set<String>) {
        extensionButtons.removeAll()

        for view in extensionOptionsStack.arrangedSubviews {
            extensionOptionsStack.removeArrangedSubview(view)
            view.removeFromSuperview()
        }

        var rowViews: [NSButton] = []
        for (index, extensionName) in extensionOptions.enumerated() {
            let button = NSButton(
                checkboxWithTitle: ".\(extensionName)",
                target: nil,
                action: nil
            )
            button.state = checkedExtensions.contains(extensionName) ? .on : .off
            button.widthAnchor.constraint(greaterThanOrEqualToConstant: 72).isActive = true
            extensionButtons[extensionName] = button
            rowViews.append(button)

            if rowViews.count == 5 || index == extensionOptions.count - 1 {
                let row = NSStackView(views: rowViews)
                row.orientation = .horizontal
                row.spacing = 8
                row.alignment = .centerY
                extensionOptionsStack.addArrangedSubview(row)
                rowViews.removeAll()
            }
        }
    }

    private func showError(_ title: String, _ message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.alertStyle = .warning
        alert.runModal()
        statusLabel.stringValue = message
    }
}

final class ServiceProvider: NSObject {
    private let runner: OpenInNvimRunner
    private let didStartOpening: () -> Void

    init(runner: OpenInNvimRunner, didStartOpening: @escaping () -> Void) {
        self.runner = runner
        self.didStartOpening = didStartOpening
    }

    @objc func openInNvim(_ pasteboard: NSPasteboard, userData: String?, error: AutoreleasingUnsafeMutablePointer<NSString?>) {
        let urls = Self.urls(from: pasteboard)

        if urls.isEmpty {
            error.pointee = "没有从 Finder 收到文件或文件夹路径。"
            return
        }

        didStartOpening()
        runner.open(urls) { error in
            if let error {
                let language = ConfigStore.shared.load().language
                NSApp.setActivationPolicy(.regular)
                NSApp.activate(ignoringOtherApps: true)
                let alert = NSAlert()
                alert.messageText = AppText.text("error.openFailed", language: language)
                alert.informativeText = error
                alert.alertStyle = .warning
                alert.runModal()
            }
            NSApp.terminate(nil)
        }
    }

    private static func urls(from pasteboard: NSPasteboard) -> [URL] {
        var urls: [URL] = []

        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
            urls.append(contentsOf: fileURLs)
        }

        if urls.isEmpty, let filenames = pasteboard.propertyList(forType: .fileURL) as? [String] {
            urls.append(contentsOf: filenames.compactMap(URL.init(string:)))
        }

        if urls.isEmpty, let filenames = pasteboard.propertyList(forType: .init("NSFilenamesPboardType")) as? [String] {
            urls.append(contentsOf: filenames.map { URL(fileURLWithPath: $0) })
        }

        return Array(Set(urls)).sorted { $0.path < $1.path }
    }
}

final class AppDelegate: NSObject, NSApplicationDelegate {
    private let runner = OpenInNvimRunner()
    private var serviceProvider: ServiceProvider?
    private var settingsWindowController: SettingsWindowController?
    private var didHandleExternalOpen = false
    private var didShowSettings = false

    func applicationDidFinishLaunching(_ notification: Notification) {
        let provider = ServiceProvider(runner: runner) { [weak self] in
            self?.didHandleExternalOpen = true
        }
        serviceProvider = provider
        NSApp.servicesProvider = provider
        NSUpdateDynamicServices()
        showSettingsIfIdle()
    }

    func application(_ application: NSApplication, open urls: [URL]) {
        didHandleExternalOpen = true
        runner.open(urls) { error in
            if let error {
                let language = ConfigStore.shared.load().language
                self.showAppForAlert()
                let alert = NSAlert()
                alert.messageText = AppText.text("error.openFailed", language: language)
                alert.informativeText = error
                alert.alertStyle = .warning
                alert.runModal()
            }
            application.terminate(nil)
        }
    }

    func applicationDidBecomeActive(_ notification: Notification) {
        showSettingsIfIdle()
    }

    func applicationShouldHandleReopen(_ sender: NSApplication, hasVisibleWindows flag: Bool) -> Bool {
        if !flag {
            showSettings()
        }
        return true
    }

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        true
    }

    private func showSettings() {
        didShowSettings = true

        if settingsWindowController == nil {
            settingsWindowController = SettingsWindowController(runner: runner)
        }

        NSApp.setActivationPolicy(.regular)
        NSApp.activate(ignoringOtherApps: true)
        settingsWindowController?.showWindow(nil)
    }

    private func showSettingsIfIdle() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { [weak self] in
            guard let self, !self.didHandleExternalOpen, !self.didShowSettings else { return }
            self.showSettings()
        }
    }

    private func showAppForAlert() {
        NSApp.setActivationPolicy(.regular)
        NSApp.activate(ignoringOtherApps: true)
    }
}

let app = NSApplication.shared
let delegate = AppDelegate()
app.delegate = delegate
app.run()
